#!/bin/bash
# Копируем реальные данные во временную память
cp /proc/cpuinfo /run/.hw_profile_cache

# Меняем название процессора
sed -i 's/^model name.*/model name\t: AMD Ryzen 7 9800X3D/g' /run/.hw_profile_cache

# Монтируем поверх оригинала
mount --bind /run/.hw_profile_cache /proc/cpuinfo
