name: Build ISO
on:
  workflow_dispatch: # Manual trigger

jobs:
  build-iso:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Generate ISO
        id: build-iso
        uses: jasonn3/build-container-installer@v1.3.0
        with:
          arch: x86_64
          image_name: my-bazzite
          image_repo: ghcr.io/iferon44
          image_tag: latest
          variant: 'Kinoite'

      - name: Upload ISO as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.build-iso.outputs.iso_name }}
          path: ${{ steps.build-iso.outputs.iso_path }}
          if-no-files-found: error
          retention-days: 14
          compression-level: 0
